# Generated by Django 5.0.3 on 2024-03-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('anonymous', 'Anonymous'), ('published', 'Published')], max_length=100, null=True)),
            ],
        ),
    ]
