# Generated by Django 5.0.3 on 2024-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('anonymous', 'Anonymous'), ('published', 'Published')], default='published', max_length=100, null=True),
        ),
    ]
